products(first: $first) {
    edges {
      node {
        title
        handle
        publishedAt
        resourcePublications(first: 5) {
          edges {
            node {
              isPublished
              publication {
                id
                name
              }
              publishDate
            }
          }
        }
      }
    }
  }
}